# Day 8
### Part 1

In [623]:
import pandas as pd
import numpy as np

In [624]:
with open('data_day8.txt') as f:
    contents = f.readlines()

In [625]:
lst_group = []
for i_content in contents:
    lst_sub_group = []
    for i_char in i_content.replace('\n',''):
        lst_sub_group.append(i_char)
    lst_group.append(lst_sub_group)

In [626]:
array_trees = np.array(lst_group)

In [627]:
array_zero = np.zeros(shape = np.shape(array_trees))

In [628]:
def func_return_populated_array_template(array_trees, array_sight):
    zero_array_template = array_sight
    for i_case in range(0,len(array_trees)):
        lst_checker = list(array_trees[i_case])
        int_figure = int(lst_checker[0])
        for i_item_pos in range(0,len(lst_checker)):
            if i_item_pos == 0:
                zero_array_template[i_case,i_item_pos] = 1
            i_item = lst_checker[i_item_pos]
            if int(i_item) > int(int_figure):
                zero_array_template[i_case,i_item_pos] = 1
                int_figure = int(i_item)
    return zero_array_template

In [629]:
# Side 1
array_zero = np.zeros(shape = np.shape(array_trees))
array_zero = func_return_populated_array_template(array_trees,array_zero)

# Side 2
array_trees = np.rot90(array_trees)
array_zero = np.rot90(array_zero)
array_zero = func_return_populated_array_template(array_trees,array_zero)

# Side 3
array_trees = np.rot90(array_trees)
array_zero = np.rot90(array_zero)
array_zero = func_return_populated_array_template(array_trees,array_zero)

# Side 4
array_trees = np.rot90(array_trees)
array_zero = np.rot90(array_zero)
array_zero = func_return_populated_array_template(array_trees,array_zero)

# Rotate back to original positions
array_trees = np.rot90(array_trees)
array_zero = np.rot90(array_zero)

In [630]:
# Original trees
array_trees

array([['2', '2', '0', ..., '1', '0', '3'],
       ['1', '1', '2', ..., '2', '0', '1'],
       ['0', '3', '0', ..., '1', '0', '0'],
       ...,
       ['2', '0', '0', ..., '3', '0', '1'],
       ['2', '1', '3', ..., '1', '3', '2'],
       ['2', '1', '1', ..., '0', '1', '0']], dtype='<U1')

In [631]:
# Visible marker
array_zero

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 0., 1.],
       [1., 1., 0., ..., 1., 0., 1.],
       ...,
       [1., 0., 0., ..., 1., 0., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [632]:
sum(sum(array_zero))

1736.0

### Part 2

In [633]:
int_height, int_width = np.shape(array_trees)[0],np.shape(array_trees)[1]

In [634]:
array_zero_move_left = np.zeros(shape = np.shape(array_trees))
array_zero_move_right = np.zeros(shape = np.shape(array_trees))
array_zero_move_up = np.zeros(shape = np.shape(array_trees))
array_zero_move_down = np.zeros(shape = np.shape(array_trees))

In [635]:
for i_height in range(0,int_height):
    for i_width in range(0,int_width):

        # Move Up
        bol_same_height_marker = False
        bol_max_heigth_changed = False
        int_marker = array_trees[i_height][i_width]
        for i_row in reversed(range(0,i_height)):
            if array_trees[i_row][i_width] < int_marker and bol_max_heigth_changed == False and bol_same_height_marker == False:
                array_zero_move_up[i_height][i_width] += 1
            elif array_trees[i_row][i_width] > int_marker and bol_max_heigth_changed == False:
                array_zero_move_up[i_height][i_width] += 1
                int_marker = array_trees[i_row][i_width]
                bol_max_heigth_changed = True
                bol_same_height_marker = False
                break
            elif array_trees[i_row][i_width] == int_marker:
#             elif array_trees[i_row][i_width] == int_marker and bol_same_height_marker == False:
                array_zero_move_up[i_height][i_width] += 1
                bol_same_height_marker = True
                break

        # Move Down
        bol_same_height_marker = False
        bol_max_heigth_changed = False
        int_marker = array_trees[i_height][i_width]
        for i_row in range(i_height+1,int_height):
            if array_trees[i_row][i_width] < int_marker and bol_max_heigth_changed == False and bol_same_height_marker == False:
                array_zero_move_down[i_height][i_width] += 1
            elif array_trees[i_row][i_width] > int_marker and bol_max_heigth_changed == False:
                array_zero_move_down[i_height][i_width] += 1
                int_marker = array_trees[i_row][i_width]
                bol_max_heigth_changed = True
                bol_same_height_marker = False
                break
            elif array_trees[i_row][i_width] == int_marker:
#             elif array_trees[i_row][i_width] == int_marker and bol_same_height_marker == False:
                array_zero_move_down[i_height][i_width] += 1
                bol_same_height_marker = True
                break

        # Move Left
        bol_same_height_marker = False
        bol_max_heigth_changed = False
        int_marker = array_trees[i_height][i_width]
        for i_col in reversed(range(0,i_width)):
            if array_trees[i_height][i_col] < int_marker and bol_max_heigth_changed == False and bol_same_height_marker == False:
                array_zero_move_left[i_height][i_width] += 1
            elif array_trees[i_height][i_col] > int_marker and bol_max_heigth_changed == False:
                array_zero_move_left[i_height][i_width] += 1
                int_marker = array_trees[i_height][i_col]
                bol_max_heigth_changed = True
                bol_same_height_marker = False
                break
            elif array_trees[i_height][i_col] == int_marker:
#             elif array_trees[i_height][i_col] == int_marker and bol_same_height_marker == False:
                array_zero_move_left[i_height][i_width] += 1
                bol_same_height_marker = True
                break
        
        # Move Right
        bol_same_height_marker = False
        bol_max_heigth_changed = False
        int_marker = array_trees[i_height][i_width]
        for i_col in range(i_width+1,int_width):
            if array_trees[i_height][i_col] < int_marker and bol_max_heigth_changed == False and bol_same_height_marker == False:
                array_zero_move_right[i_height][i_width] += 1
            elif array_trees[i_height][i_col] > int_marker and bol_max_heigth_changed == False:
                array_zero_move_right[i_height][i_width] += 1
                int_marker = array_trees[i_height][i_col]
                bol_max_heigth_changed = True
                bol_same_height_marker = False
                break
            elif array_trees[i_height][i_col] == int_marker:
#             elif array_trees[i_height][i_col] == int_marker and bol_same_height_marker == False:
                array_zero_move_right[i_height][i_width] += 1
                bol_same_height_marker = True
                break

In [636]:
array_zero_move_left

array([[0., 1., 1., ..., 1., 1., 5.],
       [0., 1., 2., ..., 5., 1., 2.],
       [0., 1., 1., ..., 1., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 2.],
       [0., 1., 2., ..., 1., 5., 1.],
       [0., 1., 1., ..., 1., 2., 1.]])

In [637]:
array_zero_move_right

array([[1., 2., 1., ..., 2., 1., 0.],
       [1., 1., 1., ..., 2., 1., 0.],
       [1., 6., 1., ..., 2., 1., 0.],
       ...,
       [3., 1., 1., ..., 2., 1., 0.],
       [2., 1., 2., ..., 1., 1., 0.],
       [3., 1., 1., ..., 1., 1., 0.]])

In [638]:
array_zero_move_up

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 2., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 2.],
       [1., 2., 2., ..., 1., 7., 7.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [639]:
array_zero_move_down

array([[4., 2., 1., ..., 1., 1., 5.],
       [3., 1., 4., ..., 2., 1., 4.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 2., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [640]:
# Answer
# 502200
# 134400
# 268800
np.max(array_zero_move_left*array_zero_move_right*array_zero_move_up*array_zero_move_down)

268800.0